[package]
name = "pokefetch"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
regex = "1.12.2"
reqwest = { version = "0.13.1", features = ["json"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0",features = ["macros", "rt-multi-thread"] }
rand = "0.9.2"
